name: Download MP4 from YouTube by ID (max-720p)

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'ID?'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get yt-dlp + ffmpeg
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          
          VIDEO_ID="${{ inputs.video_id }}"
          
          
          YOUTUBE_URL="https://www.youtube.com/watch?v=${VIDEO_ID}"
          
          echo "Downloading video with ID: ${VIDEO_ID}"
          
          
          yt-dlp -f "bestvideo[height<=720]+bestaudio" \
                 --merge-output-format mp4 \
                 -o "video.mp4" \
                 "${YOUTUBE_URL}"

          
          if [ ! -f "video.mp4" ]; then
            echo "Error: Video download failed."
            exit 1
          fi
          
          ls -lh video.mp4

      - name: Commit and Push Video
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add video.mp4
          git commit -m "Updated video with ID: ${{ inputs.video_id }}" || true
          git push
