name: download (max 720p)

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'link?'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get yt-dlp+ffmpeg
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: get-vid+dl
        run: |
          
          yt-dlp -f "bestvideo[height<=720]+bestaudio" \
                 --merge-output-format mp4 \
                 -o "video.mp4" \
                 "${{ inputs.youtube_url }}"

          
          if [ ! -f "video.mp4" ]; then
            echo "Error: Video download failed."
            exit 1
          fi
          
          ls -lh video.mp4

      - name: commit+pushVid
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add video.mp4
          git commit -m "Added video (Max 720p) from ${{ inputs.youtube_url }}" || true
          git push
